on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
name: Wiki Sync
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Sync Wiki
            uses: joeizzard/action-wiki-sync@master
            with:
                username: nftlabs
                access_token: ${{ secrets.GITHUB_TOKEN }}
                wiki_folder: docs
                commit_username: 'NFTLabs'
                commit_email: 'example@users.noreply.github.com'
                commit_message: 'action: wiki sync'
